export const catalogProducts = [
  { id: 1, nombre: 'SUMINISTRO REDES HIDRÁULICAS', imagen: '/servicios/hidraulica/logo.jpeg', slug: 'hidraulicas',
    descripcion: 'Válvulas, accesorios y tuberías para sistemas de redes hidráulicas industriales y residenciales.',
    subcategorias: [
      { id: 1, nombre: 'Válvula de Bola',    imagen: '/servicios/hidraulica/VÁLVULA BOLA.png',       categoria: 'VALVULA'   },
      { id: 2, nombre: 'Válvula Compuerta',  imagen: '/servicios/hidraulica/VÁLVULA COMPUERTA.png',  categoria: 'VALVULA'   },
      { id: 3, nombre: 'Cheque Cortina',     imagen: '/servicios/hidraulica/CHEQUE CORTINA.png',     categoria: 'VALVULA'   },
      { id: 4, nombre: 'Cheque Hidro',       imagen: '/servicios/hidraulica/CHEQUE HIDRO.png',       categoria: 'VALVULA'   },
      { id: 5, nombre: 'Válvula de Pie',     imagen: '/servicios/hidraulica/VÁLVULA DE PIE.png',     categoria: 'VALVULA'   },
      { id: 6, nombre: 'Válvula Flotadora',  imagen: '/servicios/hidraulica/VÁLVULA FLOTADORA.png',  categoria: 'VALVULA'   },
      { id: 7, nombre: 'Cheque Ranurado',    imagen: '/servicios/hidraulica/CHEQUE RANURADO.png',    categoria: 'VALVULA'   },
      { id: 8, nombre: 'Bola en Cobre',      imagen: '/servicios/hidraulica/BOLA EN COBRE.png',      categoria: 'ACCESORIO' },
      { id: 9, nombre: 'Varilla Bro-Inox',   imagen: '/servicios/hidraulica/VARILLA BRO-INOX.png',   categoria: 'ACCESORIO' },
    ],
  },
  { id: 2, nombre: 'SUMINISTRO REDES CONTRA INCENDIOS', imagen: '/servicios/incendio/incedios.jpeg', slug: 'incendios',
    descripcion: 'Equipos y accesorios certificados para sistemas de protección y extinción de incendios.',
    subcategorias: [
      { id: 1, nombre: 'Cheque Cortina Ranurado',    imagen: '/servicios/incendio/CHEQUE CORTINA RANURADO.png',    categoria: 'VALVULA'   },
      { id: 2, nombre: 'Codo Ranurado',              imagen: '/servicios/incendio/CODO RANURADO.png',              categoria: 'ACOPLE'    },
      { id: 3, nombre: 'Flanche Ranurado',           imagen: '/servicios/incendio/FLANCHE RANURADO.png',           categoria: 'ACOPLE'    },
      { id: 4, nombre: 'Gabinete',                   imagen: '/servicios/incendio/GABINETE.png',                   categoria: 'ACCESORIO' },
      { id: 5, nombre: 'Tee Ranurada',               imagen: '/servicios/incendio/TEE RANURADA.png',               categoria: 'ACOPLE'    },
      { id: 6, nombre: 'Tubería A/C Ranurada',       imagen: '/servicios/incendio/TUBERIA A⁄C RANURADA.png',       categoria: 'TUBERIA'   },
      { id: 7, nombre: 'Unión Ranurada',             imagen: '/servicios/incendio/UNION RANURADA.png',             categoria: 'ACOPLE'    },
      { id: 8, nombre: 'Válvula Angular',            imagen: '/servicios/incendio/VÁLVULA ANGULAR.png',            categoria: 'VALVULA'   },
      { id: 9, nombre: 'Válvula Compuerta Ranurada', imagen: '/servicios/incendio/VÁLVULA COMPUERTA RANURADA.png', categoria: 'VALVULA'   },
    ],
  },
  { id: 3, nombre: 'SUMINISTRO ACUEDUCTO', imagen: '/servicios/acueducto/VAL - REGULADORA DE PRESION.png', slug: 'acueducto',
    descripcion: 'Componentes para redes de distribución de agua potable y sistemas de acueducto.',
    subcategorias: [
      { id: 1, nombre: 'Cheque Cortina Bridado',   imagen: '/servicios/acueducto/CHEQUE CORTINA BRIDADO.png',   categoria: 'VALVULA'   },
      { id: 2, nombre: 'Cheque Hidro Bridado',     imagen: '/servicios/acueducto/CHEQUE HIDRO BRIDADO.png',     categoria: 'VALVULA'   },
      { id: 3, nombre: 'Filtro - Yee',             imagen: '/servicios/acueducto/FILTRO - YEE.png',             categoria: 'ACCESORIO' },
      { id: 4, nombre: 'Hidrante',                 imagen: '/servicios/acueducto/HIDRANTE.png',                 categoria: 'ACCESORIO' },
      { id: 5, nombre: 'Macromedidor',             imagen: '/servicios/acueducto/MACROMEDIDOR.png',             categoria: 'ACCESORIO' },
      { id: 6, nombre: 'Unión Dresser Multiusos',  imagen: '/servicios/acueducto/UNION - DRESSER - MULTIUSOS.png', categoria: 'ACOPLE' },
      { id: 7, nombre: 'Val. Compuerta Bridada',   imagen: '/servicios/acueducto/VAL - COMPUERTA BRIDADA.png',  categoria: 'VALVULA'   },
      { id: 8, nombre: 'Val. Extremo Liso',        imagen: '/servicios/acueducto/VAL - EXTREMO LISO.png',       categoria: 'VALVULA'   },
      { id: 9, nombre: 'Val. Reguladora de Presión', imagen: '/servicios/acueducto/VAL - REGULADORA DE PRESION.png', categoria: 'VALVULA' },
    ],
  },
  { id: 4, nombre: 'SUMINISTRO ACERO INOXIDABLE', imagen: '/servicios/acero/TUBERIA.png', slug: 'acero',
    descripcion: 'Tuberías, bridas y accesorios en acero inoxidable para aplicaciones industriales y sanitarias.',
    subcategorias: [
      { id: 1, nombre: 'Brida',              imagen: '/servicios/acero/BRIDA.png',             categoria: 'ACOPLE'    },
      { id: 2, nombre: 'Codo Roscado',       imagen: '/servicios/acero/CODO ROSCADO.png',      categoria: 'ACOPLE'    },
      { id: 3, nombre: 'Flauta',             imagen: '/servicios/acero/FLAUTA.png',             categoria: 'TUBERIA'   },
      { id: 4, nombre: 'Niple',              imagen: '/servicios/acero/NIPLE.png',              categoria: 'TUBERIA'   },
      { id: 5, nombre: 'Reducción Bushing',  imagen: '/servicios/acero/REDUCCIÓNBUSHING.png',   categoria: 'ACOPLE'    },
      { id: 6, nombre: 'Registro Esfera',    imagen: '/servicios/acero/REGISTRO ESFERA.png',    categoria: 'VALVULA'   },
      { id: 7, nombre: 'Tee Roscada',        imagen: '/servicios/acero/TEE ROSCADA.png',        categoria: 'ACOPLE'    },
      { id: 8, nombre: 'Tubería',            imagen: '/servicios/acero/TUBERIA.png',            categoria: 'TUBERIA'   },
      { id: 9, nombre: 'Unión Universal',    imagen: '/servicios/acero/UNION UNIVERSAL.png',    categoria: 'ACOPLE'    },
    ],
  },
  { id: 5, nombre: 'SUMINISTRO PVC', imagen: '/servicios/pvc/TUBERIA.png', slug: 'pvc',
    descripcion: 'Tuberías y accesorios en PVC para instalaciones hidráulicas residenciales y comerciales.',
    subcategorias: [
      { id: 1,  nombre: 'Codo',            imagen: '/servicios/pvc/CODO.png',            categoria: 'ACOPLE'    },
      { id: 2,  nombre: 'Flanche',         imagen: '/servicios/pvc/FLANCHE.png',         categoria: 'ACOPLE'    },
      { id: 3,  nombre: 'Tee',             imagen: '/servicios/pvc/TEE.png',             categoria: 'ACOPLE'    },
      { id: 4,  nombre: 'Buje',            imagen: '/servicios/pvc/BUJE.png',            categoria: 'ACOPLE'    },
      { id: 5,  nombre: 'Adaptador Macho', imagen: '/servicios/pvc/ADAPTADOR MACHO.png', categoria: 'ACOPLE'    },
      { id: 6,  nombre: 'Unión Universal', imagen: '/servicios/pvc/UNION UNIVERSAL.png', categoria: 'ACOPLE'    },
      { id: 7,  nombre: 'Tapón Hembra',    imagen: '/servicios/pvc/TAPON HEMBRA.png',    categoria: 'ACCESORIO' },
      { id: 8,  nombre: 'Tubería',         imagen: '/servicios/pvc/TUBERIA.png',         categoria: 'TUBERIA'   },
      { id: 9,  nombre: 'Limpiador',       imagen: '/servicios/pvc/LIMPIADOR.png',       categoria: 'ACCESORIO' },
      { id: 10, nombre: 'Soldadura',       imagen: '/servicios/pvc/SOLDADURA.png',       categoria: 'ACCESORIO' },
    ],
  },
]

export const catalogImages = [
  '/catalogo/catalogo-1.png',
  '/catalogo/catalogo-2.png',
  '/catalogo/catalogo-3.png',
  '/catalogo/catalogo-4.png',
  '/catalogo/catalogo-5.jpeg',
]

export const companyInfo = {
  name: 'MANHID',
  fullName: 'MANHID - Sistemas Hidráulicos',
  phone1: '310 756 5366',
  phone2: '313 494 9118',
  email: 'MANHIDKM@GMAIL.COM',
  address: 'Carrera 23 # 12-93, Los Mártires',
  city: 'Bogotá, D.C.',
  whatsapp: '+573134949118',
  hours: {
    weekdays: 'Lunes a Viernes: 8:00 AM - 6:00 PM',
    saturday: 'Sábados: 8:00 AM - 2:00 PM',
  },
  social: {
    instagram: 'https://instagram.com',
    facebook: 'https://facebook.com',
  },
}
